export const state = () => ({
  country: [
    { value: 'Fogo Island', text: 'Fogo Island (null)' },
    { value: 'Afghanistan', text: 'Afghanistan (阿富汗)' },
    { value: 'Aland Islands', text: 'Aland Islands (奧蘭群島)' },
    { value: 'Albania', text: 'Albania (阿爾巴尼亞)' },
    { value: 'Algeria', text: 'Algeria (阿爾及利亞)' },
    { value: 'American Samoa', text: 'American Samoa (美屬薩摩亞)' },
    { value: 'Andorra', text: 'Andorra (安道爾)' },
    { value: 'Angkor Wat', text: 'Angkor Wat (吳哥窟)' },
    { value: 'Angola', text: 'Angola (安哥拉)' },
    { value: 'Anguilla', text: 'Anguilla (安圭拉)' },
    { value: 'Antarctica', text: 'Antarctica (南極)' },
    {
      value: 'Antigua and Barbuda',
      text: 'Antigua and Barbuda (安地卡及巴布達)',
    },
    { value: 'Argentina', text: 'Argentina (阿根廷)' },
    { value: 'Armenia', text: 'Armenia (亞美尼亞)' },
    { value: 'Aruba', text: 'Aruba (阿魯巴)' },
    { value: 'Australia', text: 'Australia (澳大利亞)' },
    { value: 'Austria', text: 'Austria (奧地利)' },
    { value: 'Azerbaijan', text: 'Azerbaijan (亞塞拜然)' },
    { value: 'Bahamas', text: 'Bahamas (巴哈馬)' },
    { value: 'Bahrain', text: 'Bahrain (巴林)' },
    { value: 'Bangladesh', text: 'Bangladesh (孟加拉)' },
    { value: 'Barbados', text: 'Barbados (巴貝多)' },
    { value: 'Belarus', text: 'Belarus (白俄羅斯)' },
    { value: 'Belgium', text: 'Belgium (比利時)' },
    { value: 'Belize', text: 'Belize (貝里斯)' },
    { value: 'Benin', text: 'Benin (貝南)' },
    { value: 'Bermuda', text: 'Bermuda (百慕達)' },
    { value: 'Bhutan', text: 'Bhutan (不丹)' },
    { value: 'Bolivia', text: 'Bolivia (玻利維亞)' },
    {
      value: 'Bosnia and Herzegovina',
      text: 'Bosnia and Herzegovina (波士尼亞與赫塞哥維納)',
    },
    { value: 'Botswana', text: 'Botswana (波札那)' },
    { value: 'Bouvet Island', text: 'Bouvet Island (布威島)' },
    { value: 'Brazil', text: 'Brazil (巴西)' },
    {
      value: 'British Indian Ocean Territory',
      text: 'British Indian Ocean Territory (英屬印度洋領地)',
    },
    { value: 'British Virgin Islands', text: 'British Virgin Islands (null)' },
    { value: 'Brunei', text: 'Brunei (null)' },
    { value: 'Brunei Darussalam', text: 'Brunei Darussalam (汶萊)' },
    { value: 'Bulgaria', text: 'Bulgaria (保加利亞)' },
    { value: 'Burkina Faso', text: 'Burkina Faso (布吉納法索)' },
    { value: 'Burma', text: 'Burma (null)' },
    { value: 'Burundi', text: 'Burundi (蒲隆地)' },
    { value: 'Cambodia', text: 'Cambodia (柬埔寨)' },
    { value: 'Cameroon', text: 'Cameroon (喀麥隆)' },
    { value: 'Canada', text: 'Canada (加拿大)' },
    { value: 'Cape Verde', text: 'Cape Verde (佛德角)' },
    { value: 'Cayman Islands', text: 'Cayman Islands (開曼群島)' },
    {
      value: 'Central African Republic',
      text: 'Central African Republic (中非共和國)',
    },
    { value: 'Chad', text: 'Chad (查德)' },
    { value: 'Chile', text: 'Chile (智利)' },
    { value: 'China', text: 'China (中國)' },
    { value: 'Christmas Island', text: 'Christmas Island (聖誕島)' },
    { value: 'Cocos', text: 'Cocos (Keeling) Islands (科科斯（基林）群島)' },
    { value: 'Colombia', text: 'Colombia (哥倫比亞)' },
    { value: 'Comoros', text: 'Comoros (葛摩)' },
    { value: 'Congo', text: 'Congo (剛果)' },
    { value: 'Congo', text: 'Congo (Brazzaville) (null)' },
    { value: 'Congo', text: 'Congo (Kinshasa) (null)' },
    {
      value: 'Congo, The Democratic Republic Of The',
      text: 'Congo, The Democratic Republic Of The (剛果民主共和國)',
    },
    { value: 'Cook Islands', text: 'Cook Islands (庫克群島)' },
    { value: 'Costa Rica', text: 'Costa Rica (哥斯大黎加)' },
    { value: 'Cote DIvoire', text: 'Cote DIvoire (象牙海岸)' },
    { value: 'Croatia', text: 'Croatia (克羅埃西亞)' },
    { value: 'Cuba', text: 'Cuba (古巴)' },
    { value: 'Cyprus', text: 'Cyprus (賽普勒斯)' },
    { value: 'Czech Republic', text: 'Czech Republic (捷克)' },
    { value: 'Denmark', text: 'Denmark (丹麥)' },
    { value: 'Deutsch', text: 'Deutsch (德國)' },
    { value: 'Djibouti', text: 'Djibouti (吉布地)' },
    { value: 'Dominica', text: 'Dominica (多米尼克)' },
    { value: 'Dominican Republic', text: 'Dominican Republic (多明尼加)' },
    { value: 'East Timor', text: 'East Timor (null)' },
    { value: 'Ecuador', text: 'Ecuador (厄瓜多)' },
    { value: 'Egypt', text: 'Egypt (埃及)' },
    { value: 'El Salvador', text: 'El Salvador (薩爾瓦多)' },
    { value: 'Equatorial Guinea', text: 'Equatorial Guinea (赤道幾內亞)' },
    { value: 'Eritrea', text: 'Eritrea (厄利垂亞)' },
    { value: 'Estonia', text: 'Estonia (愛沙尼亞)' },
    { value: 'Ethiopia', text: 'Ethiopia (衣索比亞)' },
    { value: 'Falkland Islands', text: 'Falkland Islands (null)' },
    {
      value: 'Falkland Islands',
      text: 'Falkland Islands (Malvinas) (福克蘭群島(馬維娜斯群島))',
    },
    { value: 'Faroe Islands', text: 'Faroe Islands (法羅群島)' },
    { value: 'Fiji', text: 'Fiji (斐濟)' },
    { value: 'Finland', text: 'Finland (芬蘭)' },
    { value: 'Foreigner', text: 'Foreigner (外國人)' },
    { value: 'France', text: 'France (法國)' },
    { value: 'French Guiana', text: 'French Guiana (法屬圭亞那)' },
    { value: 'French Polynesia', text: 'French Polynesia (法屬玻里尼西亞)' },
    {
      value: 'French Southern Territories',
      text: 'French Southern Territories (法屬南部領地)',
    },
    { value: 'Gabon', text: 'Gabon (加彭)' },
    { value: 'Gambia', text: 'Gambia (甘比亞)' },
    { value: 'Georgia', text: 'Georgia (喬治亞)' },
    { value: 'Ghana', text: 'Ghana (迦納)' },
    { value: 'Gibraltar', text: 'Gibraltar (直布羅陀)' },
    { value: 'Greece', text: 'Greece (希臘)' },
    { value: 'Greenland', text: 'Greenland (格陵蘭)' },
    { value: 'Grenada', text: 'Grenada (格瑞那達)' },
    { value: 'Guadeloupe', text: 'Guadeloupe (瓜德羅普)' },
    { value: 'Guam', text: 'Guam (關島)' },
    { value: 'Guatemala', text: 'Guatemala (瓜地馬拉)' },
    { value: 'Guernsey', text: 'Guernsey (根息島)' },
    { value: 'Guinea', text: 'Guinea (幾內亞)' },
    {
      value: 'Bissau"-Guinea-Bissau',
      text: 'Bissau"-Guinea-Bissau (幾內亞比索)',
    },
    { value: 'Guyana', text: 'Guyana (蓋亞那)' },
    { value: 'Haiti', text: 'Haiti (海地)' },
    {
      value: 'Heard and McDonald Islands',
      text: 'Heard and McDonald Islands (赫德島和麥克唐納群島)',
    },
    { value: 'Holy See', text: 'Holy See (Vatican City State) (梵蒂岡)' },
    { value: 'Honduras', text: 'Honduras (宏都拉斯)' },
    { value: 'Hong Kong', text: 'Hong Kong (香港)' },
    { value: 'Hungary', text: 'Hungary (匈牙利)' },
    { value: 'Iceland', text: 'Iceland (冰島)' },
    { value: 'India', text: 'India (印度)' },
    { value: 'Indonesia', text: 'Indonesia (印尼)' },
    { value: 'Iran', text: 'Iran (null)' },
    { value: 'Iran', text: 'Iran (Islamic Republic Of) (伊朗)' },
    { value: 'Iraq', text: 'Iraq (伊拉克)' },
    { value: 'Ireland', text: 'Ireland (愛爾蘭)' },
    { value: 'Isle of Man', text: 'Isle of Man (曼島)' },
    { value: 'Israel', text: 'Israel (以色列)' },
    { value: 'Italy', text: 'Italy (義大利)' },
    { value: 'Jamaica', text: 'Jamaica (牙買加)' },
    { value: 'Japan', text: 'Japan (日本)' },
    { value: 'Jersey', text: 'Jersey (澤西島)' },
    { value: 'Johnston Atoll', text: 'Johnston Atoll (null)' },
    { value: 'Jordan', text: 'Jordan (約旦)' },
    { value: 'Kazakhstan', text: 'Kazakhstan (哈薩克)' },
    { value: 'Kenya', text: 'Kenya (肯亞)' },
    { value: 'Kiribati', text: 'Kiribati (吉里巴斯)' },
    { value: 'Kuwait', text: 'Kuwait (科威特)' },
    { value: 'Kyrgyzstan', text: 'Kyrgyzstan (吉爾吉斯)' },
    {
      value: 'Lao Peoples Democratic Republic',
      text: 'Lao Peoples Democratic Republic (寮國)',
    },
    { value: 'Laos', text: 'Laos (null)' },
    { value: 'Latvia', text: 'Latvia (拉脫維亞)' },
    { value: 'Lebanon', text: 'Lebanon (黎巴嫩)' },
    { value: 'Lesotho', text: 'Lesotho (賴索托王國)' },
    { value: 'Liberia', text: 'Liberia (賴比瑞亞)' },
    { value: 'Libya', text: 'Libya (null)' },
    {
      value: 'Libyan Arab Jamahiriya',
      text: 'Libyan Arab Jamahiriya (利比亞)',
    },
    { value: 'Liechtenstein', text: 'Liechtenstein (列支敦斯登)' },
    { value: 'Lithuania', text: 'Lithuania (立陶宛)' },
    { value: 'Luxembourg', text: 'Luxembourg (盧森堡)' },
    { value: 'Macau', text: 'Macau (澳門)' },
    { value: 'Macedonia', text: 'Macedonia (null)' },
    {
      value: 'Macedonia, the Former Yugoslav Republic Of',
      text: 'Macedonia, the Former Yugoslav Republic Of (馬其頓共和國)',
    },
    { value: 'Madagascar', text: 'Madagascar (馬達加斯加)' },
    { value: 'Malawi', text: 'Malawi (馬拉威)' },
    { value: 'Malaysia', text: 'Malaysia (馬來西亞)' },
    { value: 'Maldives', text: 'Maldives (馬爾地夫)' },
    { value: 'Mali', text: 'Mali (馬利)' },
    { value: 'Malta', text: 'Malta (馬爾他)' },
    { value: 'Marshall Islands', text: 'Marshall Islands (馬紹爾群島)' },
    { value: 'Martinique', text: 'Martinique (馬提尼克)' },
    { value: 'Mauritania', text: 'Mauritania (毛利塔尼亞)' },
    { value: 'Mauritius', text: 'Mauritius (模里西斯)' },
    { value: 'Mayotte', text: 'Mayotte (馬約特)' },
    { value: 'Mexico', text: 'Mexico (墨西哥)' },
    { value: 'Micronesia', text: 'Micronesia (null)' },
    {
      value: 'Micronesia, Federated States Of',
      text: 'Micronesia, Federated States Of (密克羅尼西亞聯邦)',
    },
    { value: 'Midway Islands', text: 'Midway Islands (null)' },
    { value: 'Moldova', text: 'Moldova (null)' },
    { value: 'Moldova', text: 'Moldova (the Republic of) (摩爾多瓦)' },
    { value: 'Monaco', text: 'Monaco (摩納哥)' },
    { value: 'Mongolia', text: 'Mongolia (蒙古)' },
    { value: 'Montenegro', text: 'Montenegro (蒙特內哥羅共和國)' },
    { value: 'Montserrat', text: 'Montserrat (蒙特塞拉特)' },
    { value: 'Morocco', text: 'Morocco (摩洛哥)' },
    { value: 'Mozambique', text: 'Mozambique (莫三比克)' },
    { value: 'Myanmar', text: 'Myanmar (緬甸)' },
    { value: 'Namibia', text: 'Namibia (納米比亞)' },
    { value: 'Nauru', text: 'Nauru (諾魯)' },
    { value: 'Nepal', text: 'Nepal (null)' },
    { value: 'Netherlands', text: 'Netherlands (荷蘭)' },
    {
      value: 'Netherlands Antilles',
      text: 'Netherlands Antilles (荷屬安地列斯)',
    },
    { value: 'New Caledonia', text: 'New Caledonia (新喀里多尼亞)' },
    { value: 'New Zealand', text: 'New Zealand (紐西蘭)' },
    { value: 'Nicaragua', text: 'Nicaragua (尼加拉瓜)' },
    { value: 'Niger', text: 'Niger (尼日)' },
    { value: 'Nigeria', text: 'Nigeria (奈及利亞)' },
    { value: 'Niue', text: 'Niue (紐埃)' },
    { value: 'Norfolk Island', text: 'Norfolk Island (諾福克島)' },
    { value: 'North Korea', text: 'North Korea (北韓)' },
    {
      value: 'Northern Mariana Islands',
      text: 'Northern Mariana Islands (北馬里亞納群島邦)',
    },
    { value: 'Norway', text: 'Norway (挪威)' },
    { value: 'Oman', text: 'Oman (阿曼)' },
    { value: 'Pakistan', text: 'Pakistan (巴基斯坦)' },
    { value: 'Palau', text: 'Palau (帛琉)' },
    { value: 'Palestine', text: 'Palestine (null)' },
    {
      value: 'Palestinian Territory, Occupied',
      text: 'Palestinian Territory, Occupied (巴勒斯坦)',
    },
    { value: 'Panama', text: 'Panama (巴拿馬)' },
    { value: 'Papua New Guinea', text: 'Papua New Guinea (巴布亞紐幾內亞)' },
    { value: 'Paraguay', text: 'Paraguay (巴拉圭)' },
    { value: 'Peru', text: 'Peru (秘魯)' },
    { value: 'Philippines', text: 'Philippines (菲律賓)' },
    { value: 'Pitcairn', text: 'Pitcairn (皮特肯群島)' },
    { value: 'Poland', text: 'Poland (波蘭)' },
    { value: 'Portugal', text: 'Portugal (葡萄牙)' },
    { value: 'Puerto Rico', text: 'Puerto Rico (波多黎各)' },
    { value: 'Qatar', text: 'Qatar (卡達)' },
    { value: 'Reunion', text: 'Reunion (留尼旺)' },
    { value: 'Romania', text: 'Romania (羅馬尼亞)' },
    { value: 'Russia', text: 'Russia (null)' },
    { value: 'Russian Federation', text: 'Russian Federation (俄羅斯)' },
    { value: 'Rwanda', text: 'Rwanda (盧安達)' },
    { value: 'Saint Barthelemy', text: 'Saint Barthelemy (聖巴瑟米)' },
    { value: 'Saint Helena', text: 'Saint Helena (聖赫倫那島)' },
    {
      value: 'Saint Kitts And Nevis',
      text: 'Saint Kitts And Nevis (聖克里斯多福與尼維斯聯邦)',
    },
    { value: 'Saint Lucia', text: 'Saint Lucia (聖露西亞)' },
    { value: 'Saint Martin', text: 'Saint Martin (聖馬丁島)' },
    {
      value: 'Saint Pierre And Miquelon',
      text: 'Saint Pierre And Miquelon (聖皮耶與密克隆群島)',
    },
    {
      value: 'Saint Vincent and the Grenadines',
      text: 'Saint Vincent and the Grenadines (null)',
    },
    {
      value: 'Saint Vincent And The Grenedines',
      text: 'Saint Vincent And The Grenedines (聖文森和格林納丁)',
    },
    { value: 'Samoa', text: 'Samoa (薩摩亞)' },
    { value: 'San Marino', text: 'San Marino (聖馬利諾)' },
    {
      value: 'Sao Tome and Principe',
      text: 'Sao Tome and Principe (聖多美普林西比)',
    },
    { value: 'Saudi Arabia', text: 'Saudi Arabia (沙烏地阿拉伯)' },
    { value: 'Senegal', text: 'Senegal (塞內加爾)' },
    { value: 'Serbia', text: 'Serbia (塞爾維亞)' },
    { value: 'Seychelles', text: 'Seychelles (塞席爾)' },
    { value: 'Sierra Leone', text: 'Sierra Leone (獅子山)' },
    { value: 'Singapore', text: 'Singapore (新加坡)' },
    { value: 'Slovakia', text: 'Slovakia (斯洛伐克)' },
    { value: 'Slovenia', text: 'Slovenia (斯洛維尼亞)' },
    { value: 'Solomon Islands', text: 'Solomon Islands (索羅門群島)' },
    { value: 'Somalia', text: 'Somalia (索馬利亞)' },
    { value: 'South Africa', text: 'South Africa (南非共和國)' },
    {
      value: 'South Georgia and the Islands',
      text: 'South Georgia and the Islands (null)',
    },
    {
      value: 'South Georgia and the South Sandwich Islands',
      text:
        'South Georgia and the South Sandwich Islands (南喬治亞島與南三明治群島)',
    },
    { value: 'South Korea', text: 'South Korea (南韓)' },
    { value: 'South Sudan', text: 'South Sudan (null)' },
    { value: 'Spain', text: 'Spain (西班牙)' },
    { value: 'Sri Lanka', text: 'Sri Lanka (斯里蘭卡)' },
    { value: 'Sudan', text: 'Sudan (蘇丹)' },
    { value: 'Suriname', text: 'Suriname (蘇利南)' },
    { value: 'Svalbard', text: 'Svalbard (null)' },
    {
      value: 'Svalbard And Jan Mayen',
      text: 'Svalbard And Jan Mayen (斯瓦巴及尖棉島)',
    },
    { value: 'Swaziland', text: 'Swaziland (史瓦濟蘭王國)' },
    { value: 'Sweden', text: 'Sweden (瑞典)' },
    { value: 'Switzerland', text: 'Switzerland (瑞士)' },
    { value: 'Syria', text: 'Syria (null)' },
    { value: 'Syrian Arab Republic', text: 'Syrian Arab Republic (敘利亞)' },
    { value: 'Taiwan', text: 'Taiwan (台灣)' },
    { value: 'Tajikistan', text: 'Tajikistan (塔吉克)' },
    { value: 'Tanzania', text: 'Tanzania (null)' },
    {
      value: 'Tanzania, United Republic of',
      text: 'Tanzania, United Republic of (坦尚尼亞聯合共和國)',
    },
    { value: 'Thailand', text: 'Thailand (泰國)' },
    {
      value: 'The Federal Democratic Republic of Nepal',
      text: 'The Federal Democratic Republic of Nepal (尼泊爾)',
    },
    { value: 'Leste"-Timor-Leste', text: 'Leste"-Timor-Leste (東帝汶)' },
    { value: 'Togo', text: 'Togo (多哥)' },
    { value: 'Tokelau', text: 'Tokelau (托克勞)' },
    { value: 'Tonga', text: 'Tonga (東加)' },
    { value: 'Trinidad and Tobago', text: 'Trinidad and Tobago (千里達)' },
    { value: 'Tunisia', text: 'Tunisia (突尼西亞)' },
    { value: 'Turkey', text: 'Turkey (土耳其)' },
    { value: 'Turkmenistan', text: 'Turkmenistan (土庫曼)' },
    {
      value: 'Turks and Caicos Islands',
      text: 'Turks and Caicos Islands (土克凱可群島群島)',
    },
    { value: 'Tuvalu', text: 'Tuvalu (吐瓦魯)' },
    { value: 'Uganda', text: 'Uganda (烏干達)' },
    { value: 'Ukraine', text: 'Ukraine (烏克蘭)' },
    {
      value: 'United Arab Emirates',
      text: 'United Arab Emirates (阿拉伯聯合大公國)',
    },
    { value: 'United Kingdom', text: 'United Kingdom (英國)' },
    { value: 'United States', text: 'United States (美國)' },
    {
      value: 'United States Minor Outlying Islands',
      text: 'United States Minor Outlying Islands (美國本土外小島嶼)',
    },
    { value: 'Uruguay', text: 'Uruguay (烏拉圭)' },
    { value: 'Uzbekistan', text: 'Uzbekistan (烏茲別克)' },
    { value: 'Vanuatu', text: 'Vanuatu (萬那杜)' },
    { value: 'Venezuela', text: 'Venezuela (委內瑞拉)' },
    { value: 'Viet Nam', text: 'Viet Nam (越南)' },
    { value: 'Vietnam', text: 'Vietnam (null)' },
    { value: 'Virgin Islands', text: 'Virgin Islands (null)' },
    {
      value: 'Virgin Islands, British',
      text: 'Virgin Islands, British (英屬維京群島)',
    },
    {
      value: 'Virgin Islands, U.S.',
      text: 'Virgin Islands, U.S. (美屬維京群島)',
    },
    { value: 'Wake Island', text: 'Wake Island (null)' },
    {
      value: 'Wallis and Futuna',
      text: 'Wallis and Futuna (瓦利斯和富圖納群島)',
    },
    { value: 'West Bank', text: 'West Bank (null)' },
    { value: 'Western Sahara', text: 'Western Sahara (西撒哈拉)' },
    { value: 'Yemen', text: 'Yemen (葉門)' },
    { value: 'Zambia', text: 'Zambia (尚比亞)' },
    { value: 'Zimbabwe', text: 'Zimbabwe (辛巴威)' },
  ],
  phoneCode: [
    { value: '+1', text: '+1' },
    { value: '+1264', text: '+1264' },
    { value: '+1268', text: '+1268' },
    { value: '+1441', text: '+1441' },
    { value: '+1473', text: '+1473' },
    { value: '+1758', text: '+1758' },
    { value: '+1767', text: '+1767' },
    { value: '+1876', text: '+1876' },
    { value: '+20', text: '+20' },
    { value: '+212', text: '+212' },
    { value: '+233', text: '+233' },
    { value: '+234', text: '+234' },
    { value: '+237', text: '+237' },
    { value: '+243', text: '+243' },
    { value: '+248', text: '+248' },
    { value: '+249', text: '+249' },
    { value: '+250', text: '+250' },
    { value: '+254', text: '+254' },
    { value: '+256', text: '+256' },
    { value: '+261', text: '+261' },
    { value: '+297', text: '+297' },
    { value: '+30', text: '+30' },
    { value: '+32', text: '+32' },
    { value: '+33', text: '+33' },
    { value: '+34', text: '+34' },
    { value: '+351', text: '+351' },
    { value: '+352', text: '+352' },
    { value: '+353', text: '+353' },
    { value: '+354', text: '+354' },
    { value: '+358', text: '+358' },
    { value: '+380', text: '+380' },
    { value: '+381', text: '+381' },
    { value: '+389', text: '+389' },
    { value: '+39', text: '+39' },
    { value: '+40', text: '+40' },
    { value: '+41', text: '+41' },
    { value: '+43', text: '+43' },
    { value: '+45', text: '+45' },
    { value: '+46', text: '+46' },
    { value: '+47', text: '+47' },
    { value: '+49', text: '+49' },
    { value: '+502', text: '+502' },
    { value: '+503', text: '+503' },
    { value: '+504', text: '+504' },
    { value: '+505', text: '+505' },
    { value: '+507', text: '+507' },
    { value: '+509', text: '+509' },
    { value: '+52', text: '+52' },
    { value: '+54', text: '+54' },
    { value: '+55', text: '+55' },
    { value: '+57', text: '+57' },
    { value: '+58', text: '+58' },
    { value: '+591', text: '+591' },
    { value: '+595', text: '+595' },
    { value: '+598', text: '+598' },
    { value: '+60', text: '+60' },
    { value: '+61', text: '+61' },
    { value: '+62', text: '+62' },
    { value: '+64', text: '+64' },
    { value: '+65', text: '+65' },
    { value: '+66', text: '+66' },
    { value: '+674', text: '+674' },
    { value: '+675', text: '+675' },
    { value: '+676', text: '+676' },
    { value: '+679', text: '+679' },
    { value: '+7', text: '+7' },
    { value: '+81', text: '+81' },
    { value: '+82', text: '+82' },
    { value: '+852', text: '+852' },
    { value: '+855', text: '+855' },
    { value: '+86', text: '+86' },
    { value: '+880', text: '+880' },
    { value: '+886', text: '+886' },
    { value: '+90', text: '+90' },
    { value: '+91', text: '+91' },
    { value: '+92', text: '+92' },
    { value: '+93', text: '+93' },
    { value: '+94', text: '+94' },
    { value: '+960', text: '+960' },
    { value: '+962', text: '+962' },
    { value: '+964', text: '+964' },
    { value: '+965', text: '+965' },
    { value: '+966', text: '+966' },
    { value: '+967', text: '+967' },
    { value: '+971', text: '+971' },
    { value: '+973', text: '+973' },
    { value: '+975', text: '+975' },
    { value: '+995', text: '+995' },
    { value: '+998', text: '+998' },
  ],
})

export const getters = {
  GET_COUNTRY: (state) => state.country,
  GET_PHONECODE: (state) => state.phoneCode,
}
